### PR TITLE
Update tokenizer to no longer accept octals (without the prefix) and the long suffix

### PR DESCRIPTION
**Pull request by slozier**

### CODE REVIEW

**Comment by slozier** [comment]
Hmm, maybe hold off on this one, I don't think it's quite right. For example `000` should be valid but it's not.

**Comment by slozier** [comment]
Seems to work now. Any idea if there are tests for this type of stuff?

**Comment by slide** [comment]
test_int.py has some octal tests, but we can't run tests yet because the parser isn't up to snuff. https://github.com/IronLanguages/ironpython3/blob/master/Src/StdLib/Lib/test/test_int.py#L138

**Comment by slide** [comment]
One thing I have been doing is copying some of the tests into a new file and then using -S to skip import of site.py.

**Comment by slide** [comment]
Are you happy with this? If so, I'll go ahead and merge it.

**Comment by slozier** [comment]
@slide Yes. Should be fine for now.

**Pull request merged**
