### PR TITLE
Fix serialization of non-int-based enum instances

### PR DESCRIPTION
**Pull request by BCSharp**
Also applies to pickling.

### CODE REVIEW

**Review by slozier — APPROVED** [review]
Seems fine. I'm surprised there isn't a better way to check for primitive types (e.g. `type.IsPrimitive`).

**Comment by BCSharp** [comment]
There is. It's `type.IsPrimitive` 😄

**Comment by BCSharp** [comment]
Well, it turns out the test `!type.IsPrimitive` is not right by itself. `decimal` and `DBNull` are not primitive. I'll submita PR soon.

**Comment by slozier** [comment]
Ah right, didn't notice those were the list.

**Pull request merged**
