### PR TITLE
Fix #294

### LINKED ISSUE #294: "recipe failed" when building on Ubuntu
Hi,

I tried the following to build the code:

- `git clone [...] --recurse`
- `make`

I get an error, with very little information:

```
Configuration: Debug Platform: AnyCPU
		Configuration: Debug Platform: AnyCPU
Makefile:4: recipe for target 'debug' failed
make: *** [debug] Error 1
```

What exactly does this mean? I checked the `Makefile` and ran line 4 (`xbuild Build.proj /t:Build /p:Mono=true /p:BuildFlavour=Debug /p:Platform="Any CPU" /verbosity:minimal /nologo`) manually, but it just prints the same first two lines (configuration: Debug ...) and nothing apparently happens.

### PR DESCRIPTION
**Pull request by slozier**

### CODE REVIEW

**Comment by ashes999** [comment]
I cloned your repository and checked out the `fix294` branch, then ran `make`. I still see the same error.

**Comment by slide** [comment]
I'm not sure this is needed.

**Comment by slozier** [comment]
I get a "warning as error" when I try to build without it.

**Comment by ashes999** [comment]
I also get a warning-as-error when I build without it.

**Pull request merged**
