### PR TITLE
Enable 32-bit tests during CI

### PR DESCRIPTION
**Pull request by slozier**

### CODE REVIEW

**Comment by Lamparter** [comment]
@slozier what's stopping this from being merged?

**Comment by slozier** [comment]
I don't remember why I left this one as a draft. Maybe something was failing? Or Windows 11 being 64-bit only made testing it less interesting. I guess I can rebase and see if anything is failing.

**Comment by Lamparter** [comment]
How is the check still running?
I'm surprised it's taking this long

**Comment by slozier** [comment]
Ahh, a bunch of tests are not actually running in 32-bit mode because the process runner is launching ipy.exe. Seems vaguely familiar - probably why I moved it to draft in the first place. Guess I should have left a note. :smile:

**Comment by slozier** [comment]
Closing this one as it just increases CI time considerably for little to no gain.

**Pull request closed without merging**
