### PR TITLE
Update Parser.cs

### PR DESCRIPTION
**Pull request by m1090c**
In the DebugInfoRewriter class within Microsoft.Dynamic.dll, the VisitParameter method adds debugging information starting from the second Expression. This causes the first line of code to lack debugging information, making it undebuggable.

### CODE REVIEW

**Comment by slozier** [comment]
Thanks the PR. Unfortunately this appears to break all tests. Could you maybe provide a code example of what you're trying to fix?

**Comment by m1090c** [comment]
Using the SetTrace method in IronPython.Hosting.Python to set a traceback.
Class:IronPython.Hosting.Python
public delegate TracebackDelegate TracebackDelegate(TraceBackFrame frame, string result, object payload);
/// <summary>
/// Enables call tracing for the current thread in this ScriptEngine.  
/// 
/// TracebackDelegate will be called back for each function entry, exit, exception, and line change.
/// </summary>
public static void SetTrace(this ScriptEngine/*!*/ engine, TracebackDelegate traceFunc) {
    SysModule.settrace(GetPythonContext(engine).SharedContext, traceFunc);
}

When executing simple assignment statements, such as:
x = 1  
y = 2  
in the result output, only the y = 2 statement is marked with TraceEventKind.TracePoint. The debug marker for x = 1 is skipped.

Class:IronPython.Runtime.PythonTracebackListener
private void DispatchTrace(List<FunctionStack> thread, Debugging.TraceEventKind kind, object payload, TracebackDelegate traceDispatch, object traceDispatchObject, TraceBackFrame pyFrame) {
    object args = null;

    // Prepare the event
    string traceEvent = String.Empty;
    switch (kind) {
        case Debugging.TraceEventKind.FrameEnter: traceEvent = "call"; break;
        case Debugging.TraceEventKind.TracePoint: traceEvent = "line"; break;
        case Debugging.TraceEventKind.Exception:
            traceEvent = "exception";
            object pyException = PythonExceptions.ToPython((Exception)payload);
            object pyType = ((IPythonObject)pyException).PythonType;
            args = PythonTuple.MakeTuple(pyType, pyException, new TraceBack(null, pyFrame));
            break;
        case Debugging.TraceEventKind.FrameExit:
            traceEvent = "return";
            args = payload;
            break;
    }

In reviewing the debug information generation method in DebugInfoRewriter from Microsoft.Dynamic, the int locationCookie = this._locationCookie; starts from 0. To address this, I added an EmptyStatement to handle the issue, but this might only be a temporary solution. Perhaps you have a better approach to resolve it.

protected override Expression VisitDebugInfo(DebugInfoExpression node)
		{
			if (node.IsClear)
			{
				return Expression.Empty();
			}
			if (node.Document == null)
			{
				throw new InvalidOperationException(string.Format(CultureInfo.CurrentCulture, ErrorStrings.DebugInfoWithoutSymbolDocumentInfo, new object[] { this._locationCookie }));
			}
			DebugSourceFile debugSourceFile = this._debugContext.GetDebugSourceFile(string.IsNullOrEmpty(node.Document.FileName) ? "<compile>" : node.Document.FileName);
			int locationCookie = this._locationCookie;
			this._locationCookie = locationCookie + 1;
			int num = locationCookie;
			Expression expression2;
			if (!this._transformToGenerator)
			{
				Expression expression;
				if (num == 0)
				{
					expression = Expression.Empty();
				}
				else
				{
					expression = Expression.Call(typeof(RuntimeOps).GetMethod("OnTraceEvent"), this._thread, Utils.Constant(num), Expression.Convert(Expression.Constant(null), typeof(Exception)));
				}
				expression2 = Expression.Block(Expression.Assign(this._debugMarker, Utils.Constant(num)), Expression.IfThen(Expression.GreaterThan(Expression.Property(this._sourceFilesToVariablesMap[debugSourceFile], "Mode"), Expression.Constant(1)), Expression.IfThen(Expression.OrElse(Expression.Equal(Expression.Property(this._sourceFilesToVariablesMap[debugSourceFile], "Mode"), Expression.Constant(3)), Expression.ArrayIndex(this._traceLocations, Utils.Constant(num))), Expression.Block(this._pushFrame ?? Expression.Empty(), expression))));
			}
			else
			{
				expression2 = Expression.Block(new Expression[] { Utils.YieldReturn(this._generatorLabelTarget, this._debugYieldValue, num) });
				if (this._currentLocals.Count > 0)
				{
					BlockExpression blockExpression = this._currentLocals.Peek();
					IList<VariableInfo> list;
					if (!this._variableScopeMapCache.TryGetValue(blockExpression, out list))
					{
						list = new List<VariableInfo>();
						BlockExpression[] array = this._currentLocals.ToArray();
						for (int i = array.Length - 1; i >= 0; i--)
						{
							foreach (ParameterExpression parameterExpression in array[i].Variables)
							{
								list.Add(this._localsToVarInfos[parameterExpression]);
							}
						}
						this._variableScopeMapCache.Add(blockExpression, list);
					}
					this._variableScopeMap.Add(num, list);
				}
				DebugSourceSpan debugSourceSpan = new DebugSourceSpan(debugSourceFile, node.StartLine, node.StartColumn, node.EndLine, node.EndColumn);
				this._markerLocationMap.Add(num, debugSourceSpan);
			}
			return expression2;
		}

**Comment by m1090c** [comment]
@slozier slozier

**Comment by slozier** [comment]
Can reproduce the issue with the following:
```py
import sys

calls = []

def trace_func(frame, event, arg):
    calls.append(f"{event} {frame.f_lineno}")
    return trace_func

sys.settrace(trace_func)
exec('x=1\ny=2')
sys.settrace(None)

assert calls == ['call 1', 'line 1', 'line 2', 'return 2']
```

I wonder if we can just drop the branch in `VisitDebugInfo`...
```cs
if (num == 0)
{
	expression = Expression.Empty();
}
```

**Comment by m1090c** [comment]
The issue doesn't occur if the first line of the code contains an importstatement. The issue only arises when the first line is an AssignmentStatement.This issue doesn't occur in Python either.

**Pull request closed without merging**
