### PR TITLE
Prefer BigInteger to UInt64 conversion over to Int32/UInt32

### PR DESCRIPTION
**Pull request by BCSharp**
This resolves the problem with `System.UIntPtr` from #868.  `BigInteger` to `UInt64` is now performed at narroving level _One_, just like for `Int64`. This puts it at a higher preference level than the conversion from `BigInteger` to `Int32`/`UInt32`, which are done at narrowing level _All_ (lowest).

It does not address the fact that `double`/`float` will be preferred over `ulong`. This is because conversion from `BigInteger` to `Double` and `Single` is already done at narrowing level _None_ (highest priority), which normally means no data loss. This is not entirely accurate:

```
>>> import System 
>>> int(float(System.UInt64.MaxValue)) - System.UInt64.MaxValue
1
>>> int(float(0xFFFFFFFFFFFFFFFF)) - 0xFFFFFFFFFFFFFFFF
-2047
>>> System.UInt64.MaxValue - 0xFFFFFFFFFFFFFFFF        
0
```

However the alternative, that is, to prefer `ulong` over `double` seems worse, because `BigInteger` can really be out of range. But I think that to prefer the conversion to `Single` is really a mistake. And this is what is happening with `Math.Max`:

```
>>> hex(int(System.Math.Max(0xFFFFFFF000000000,1)))    
'0x10000000000000000'
>>> type(System.Math.Max(0xFFFFFFF000000000,1))    
<class 'Single'>
```

Therefore at least I would like to remove the preference of `Single`.

### CODE REVIEW

**Comment by slozier** [comment]
Apologies for the delay, I wanted to try this against some of the binder tests (which were not in working order). I've pushed the tests to https://github.com/IronLanguages/ironpython3/pull/893. I have not yet merged the tests since it would cause this PR to fail.

This appears to break `str(System.Int64())` (from `test_methoddispatch`). Also getting some failures in `test_methodbinder2` although those may be expected?

**Comment by BCSharp** [comment]
> Apologies for the delay

No problem, I have been preoccupied with other projects myself.

> This appears to break `str(System.Int64())` (from `test_methoddispatch`).

Yes, it does, due to the removal of line 564 in Src/IronPython/Runtime/Converter.cs in commit 1f36bc4. This change deprioritized conversion from `BigInteger` to `Single`, but a side effect is that overloads with `BigInteger` and `Single` are now ambiguous. For this particular case (`str(...)` constructor) it could have been mitigated by either removing the `Single` overload (it seems it does not add anything that the `Double` overload couldn't handle?) or adding a proper `Int64` overload to the collection (in C#, calling `StringOps.__new__` with `Int64` already gets rejected as ambiguous). So the changed behaviour is consistent with C#, but in IronPython, we can do better. 

I think the root cause of the whole issue here is the hardcoded rules in `Converter.HasImplicitNumericConversion` that pretend that there is an implicit conversion from `BigInteger` to `Single`, `Double`, and `Complex`, while in reality no such implicit conversions exist. On top of that, the code assumes that if there is an implicit conversion, it will be lossless so it qualifies when the narrowing level is _None_. This creates all kinds of problems with `BigInteger`, which in a general case cannot be losslessly converted to any of those types. I think this should be eventually rectified, but in this PR I tried to limit the changes to minimum, leaving a bigger overhaul for another PR (or maybe several PRs). It would also help if we had better test coverage of the resolver, so I appreciate your work in #893.

One of the rules the resolver uses is that in case of several candidates, the most narrow type gets the highest preference. This makes sense for reference types, because it favours a derived type over a base type. It is more questionable for numeric types but it can still work fine assuming that the "narrowness" is correctly defined (in the sense that casting from a narrower type to a wider type never causes information loss). Pretending that there is a lossless conversion from `BigInteger` to `Single` solves the ambiguity in the `str` constructor, but creates unwanted side effects. I think this is not a proper way or place of resolving this ambiguity. It seems to me that the intended place for it is the `SelectBestConversionFor` override. So my proposed solution is a new rule that breaks the ambiguity by preferring conversions that maintain "integerness". 

> Also getting some failures in test_methodbinder2

I haven't had time to look into it yet.

**Comment by BCSharp** [comment]
>> Also getting some failures in `test_methodbinder2`

> I haven't had time to look into it yet.

Looking into all currently occurring failures and errors in `test_methodbinder2`, I'd say they are expected. That is, the way how IronPython resolves the overloads is what I expect, and what the tests expect is incorrect.

**Comment by slozier** [comment]
> > > Also getting some failures in `test_methodbinder2`
> 
> > I haven't had time to look into it yet.
> 
> Looking into all currently occurring failures and errors in `test_methodbinder2`, I'd say they are expected. That is, the way how IronPython resolves the overloads is what I expect, and what the tests expect is incorrect.

Sounds good. I'll merge in the other PR then patch this one to get `test_methodbinder2` working. Will make it easier to see what changed as a consequence.

**Comment by slozier** [comment]
Alright, I finally got around to patching `test_methodbinder2`. I just made it pass but did not do any checks to make sure the overload resolution changes make sense. Hopefully I can find a bit of time to do that this weekend.

**Pull request merged**
