### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by slozier**
- Export `os.symlink` on Windows (even if it's not currently implemented)
- Change map to an `IEnumerator` (similar to https://github.com/IronLanguages/ironpython3/pull/242)

### CODE REVIEW

**Comment by slozier** [comment]
Interesting, this change made the following issue pop up:
```
>>> print(*map(ord, "abc"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: print() argument after * must be a sequence, not map
```
It fails for any `IEnumerator` which is not also `IEnumerable` (e.g. map and filter in this PR).

The easy fix would be to implement `IEnumerable` as well, but it would not resolve the following case:
```Python
class test:
  def __iter__(self):
    return iter([1])

print(*test())
```
which fails with:
> TypeError: print() argument after * must be a sequence, not Object_1$1

Note that if the failure were valid, the error message should be:
> TypeError: print() argument after * must be an iterable, not test

**Comment by BCSharp** [comment]
I don't know if it is related, but during debugging I've noticed that occasionally the assert in `Runtime/Enumerate.cs`, line 287, fails.

**Comment by slozier** [comment]
Haven't noticed that one. Looking at usage it seems unrelated. May be worth trying to find a repro though...

**Comment by BCSharp** [comment]
> May be worth trying to find a repro though...

It turns out it was triggered by debug support code I wrote to investigate pickling of byte iterators. Nothing of it ended in the repository.

**Pull request merged**
