### PR TITLE
Resolve sys.builtin_module_names being unsorted (#875)

### PR DESCRIPTION
**Pull request by syn2083**
Hopefully simple PR, added an Array.Sort() onto the array generated when getting the builtin module names prior to publication, and after verifying protocol, added a test (verified it worked, though the section is ignored in general) to Tests\modules\system_related\test_sys.py

def test_builtin_module_names(self):
    ...

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/IronLanguages/ironpython3?pullRequest=919) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/IronLanguages/ironpython3?pullRequest=919) before we can accept your contribution.<br/><br/>:x: syn2083 [sign now](https://cla.dotnetfoundation.org/IronLanguages/ironpython3?pullRequest=919)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/IronLanguages/ironpython3?pullRequest=919) it.</sub>

**Comment by slozier** [comment]
@syn2083 You should create a branch for your PR. It looks like when you pushed your fix for 848 to your master it got added to this.

**Comment by syn2083** [comment]
Ah, sorry, been out of the collaborative game for a while ran into a few forgotten points.

I can fix that up and resubmit. Thanks.

**Comment by slozier** [comment]
No worries. Glad for the PRs!

**Pull request closed without merging**
