### PR TITLE
Add mutex to prevent running same test in parallel

### PR DESCRIPTION
**Pull request by slozier**

### CODE REVIEW

**Comment by slozier** [comment]
I don't like how it will "bloat" the reported test time when it's actually waiting for the test to start. Will see if I can find a way to avoid that.

**Comment by slozier** [comment]
I tried moving the mutex to setup/teardown in the hope that those would not be included in the test duration, but without success. I'm open to suggestions, otherwise this is ready for review.

**Comment by BCSharp** [comment]
I have no better ideas. I was only wondering whether the name of the mutex should be in the "Global\" namespace but I don't know the CI configuration and how it manages test runs.

**Comment by slozier** [comment]
> I was only wondering whether the name of the mutex should be in the "Global" namespace

I also have no idea. :smile: I guess the worst case scenario we get some test failures due to resource contention.

**Pull request merged**
