### PR TITLE
Give more time in test__socket for server to start up

### PR DESCRIPTION
**Pull request by BCSharp**

### CODE REVIEW

**Review by slozier — APPROVED** [review]
What an ugly test... Fine by me. 😊

**Comment by slozier** [comment]
@BCSharp Sorry, I hijacked your PR. Hopefully I didn't break things.

**Comment by BCSharp** [comment]
OMG, I coudn't stop laughing... It is an ugly test indeed. For me, every time I saw `test__socket` failing again, I was ready to shoot myself. This was not something I wanted to put my attention to. Thanks for any improvements and fixes.

On another note, I see that the GitHub macOS CI is failing because of lack of funds? It there a monthly limit of sorts? If so, when does it reset? How did it get chewed up? Did the hundreds of restructure commits pushed to GitHub one by one eat up all the budget?

**Comment by slozier** [comment]
> On another note, I see that the GitHub macOS CI is failing because of lack of funds? It there a monthly limit of sorts? If so, when does it reset? How did it get chewed up? Did the hundreds of restructure commits pushed to GitHub one by one eat up all the budget?

No idea about the funds thing, as far as I can tell it's going through the .NET Foundation...

**Pull request merged**
