### PR TITLE
Improve perf while iterating over globals

### PR DESCRIPTION
**Pull request by slozier**
Resolves https://github.com/IronLanguages/ironpython3/issues/1309

### CODE REVIEW

**Comment by BCSharp** [comment]
Is this a regression?

**Comment by slozier** [comment]
@BCSharp Yes and no I guess. Yes in that perf is horrible compared to ipy2, no in that the only change compared to ipy2 is return value of `dict.keys` changed from a list to a `dict_keyiterator`. This is just a quick fix for this specific scenario and doesn't really resolve the underlying perf issue.

The underlying issue is that the dictionary iterators call `DictionaryStorage.Count` to check for size changes at every step and this is not cheap for certain storages.

**Comment by BCSharp** [comment]
Would it help to cache the size and invalidate it only on dictionary changes?

**Comment by slozier** [comment]
That might work, but I'm not super comfortable with this part of the codebase so not something I want to mess with right now. Will probably need to revisit if I ever get to making dicts preserve insertion order.

**Pull request merged**
