### PR TITLE
[WIP][RFC] Add initial Travis CI support

### PR DESCRIPTION
**Pull request by moto-timo**
Signed-off-by: Tim Orling timothy.t.orling@linux.intel.com

### CODE REVIEW

**Comment by moto-timo** [comment]
Close and re-open to try to trigger a Travis CI build.

**Comment by moto-timo** [comment]
NOTE: The build fails and Travis CI doesn't catch it. The ```make``` command exits with ```0``` so Travis thinks "All is well. Carry on."

**Comment by slide** [comment]
Is this valid anymore?

**Comment by moto-timo** [comment]
Superseded.

**Pull request closed without merging**
