### PR TITLE
Fix #395

### LINKED ISSUE #395: Change sys.platform to match CPython
Having `sys.platform == "cli"` is one of those things which just causes a bunch of compatibility issues in IronPython 2.7. For IronPython 3 we should consider changing it to a standard value. There are other mechanisms such as `platform.python_implementation() == "IronPython"` which can be used to figure out if we're running on IronPython or not.

Note that there's also `sys.implementation` since Python 3.3 which we could use so we don't have to `import platform` to do checks in the std lib.

### PR DESCRIPTION
**Pull request by slide**
```
IronPython 3.4.0a0 (3.4.0.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> assert sys.platform =="win32"
>>> assert sys.platform == "cli"
>>> assert not sys.platform != "win32"
>>> assert not sys.platform != "cli"
>>> assert not sys.platform == "bla"
>>> assert sys.platform != "bla"
```

### CODE REVIEW

**Comment by slide** [comment]
The one thing I am not happy with in this is that `type(sys.platform)` is not `str`

**Comment by slozier** [comment]
Yeah, unfortunately `assert "cli" == sys.platform` fails.

**Comment by slide** [comment]
Yeah, the binder needs to look for the subclass and stuff like in the fix for str and OrderedSet stuff I implemented.

**Comment by slozier** [comment]
Probably needs to be fixed at the `PythonType` level. Seems to me like `Extensible<string>` should have `str` in its bases.

**Comment by slozier** [comment]
Something like adding
```C#
} else if (TryReplaceExtensibleWithBase(_underlyingSystemType, out baseType) && !baseType.IsGenericParameter) {
    // Extensible<x> inherits from x
} else {
```
to `PythonType.AddSystemBases`...

**Comment by slide** [comment]
I'm closing this out because I think we can make a breaking change here and move to `sys.implementation.name` instead with IronPython3.

**Pull request closed without merging**
